apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-checker
spec:
  template:
    spec:
      tolerations:
      - key: kubernetes.azure.com/scalesetpriority
        operator: Equal
        value: spot
        effect: NoSchedule
