apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demoapp
resources:
  - namespace.yaml
  - secret-provider-class.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - serviceaccount.yaml
  - networkpolicy.yaml
