apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: azure-sync
spec:
  provider: azure
  secretObjects:
  - secretName: demoapp-secret
    type: Opaque
    data:
    - objectName: redis-server
      key: redis-server
    - objectName: redis-password
      key: redis-password
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: ${mi_kubelet_id}
    keyvaultName: ${demoapp_key_vault_name}
    objects: |
      array:
        - |
          objectName: redis-server
          objectType: secret
        - |
          objectName: redis-password
          objectType: secret
    tenantId: ${tenant_id}
