apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: session-checker
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: session-checker
  policy:
    semver:
      range: 1.2.x
