apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: nginx
      spec:
        # Default values
        # https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml
        values:
          controller:
            tolerations:
            - key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
              effect: NoSchedule
            - key: CriticalAddonsOnly
              operator: Exists
          defaultBackend:
            tolerations:
            - key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
              effect: NoSchedule
            - key: CriticalAddonsOnly
              operator: Exists
    target:
      kind: HelmRelease
      name: nginx
      namespace: nginx
  - patch: |-
      apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      metadata:
        name: chaos-mesh
      spec:
        # Default values
        # https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml
        values:
          chaosDaemon:
            tolerations:
            - key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
              effect: NoSchedule
          dashboard:
            tolerations:
            - key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
              effect: NoSchedule
    target:
      kind: HelmRelease
      name: chaos-mesh
      namespace: chaos-testing



