
kind: ConfigMap
apiVersion: v1
metadata:
  name: container-azm-ms-agentconfig
data:
  schema-version: v1
  config-version: v1
  log-data-collection-settings: |-
    [log_collection_settings]
      [log_collection_settings.stdout]
        enabled = true
        exclude_namespaces = ["kube-system"]
      [log_collection_settings.stderr]
        enabled = true
        exclude_namespaces = ["kube-system"]
      [log_collection_settings.env_var]
        enabled = true
      [log_collection_settings.enrich_container_logs]
        enabled = false
      [log_collection_settings.collect_all_kube_events]
        enabled = false
      [log_collection_settings.schema]
        containerlog_schema_version = "v2"
