apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: chaos-mesh
spec:
  releaseName: chaos-mesh
  chart:
    spec:
      chart: chaos-mesh
      sourceRef:
        kind: HelmRepository
        name: chaos-mesh
        namespace: flux-system
      version: "2.6.2"
  interval: 5m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  # Default values
  # https://github.com/chaos-mesh/chaos-mesh/blob/master/helm/chaos-mesh/values.yaml
  values:
    controllerManager:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
    chaosDaemon:
      runtime: containerd
      socketPath: /run/containerd/containerd.sock
    dnsServer:
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
