apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/demoapp
  - ../../base/demoapp/image-update
patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: session-checker
      spec:
        template:
          spec:
            tolerations:
            - key: kubernetes.azure.com/scalesetpriority
              operator: Equal
              value: spot
              effect: NoSchedule
    target:
      kind: Deployment
      name: session-checker
      namespace: demoapp
