apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nginx
spec:
  chart:
    spec:
      chart: ingress-nginx
      version: "4.0.17"
  # Default values
  # https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml
  values:
    controller:
      service:
        annotations:
          service.beta.kubernetes.io/azure-load-balancer-internal: "true"
          service.beta.kubernetes.io/azure-load-balancer-internal-subnet: ${demoapp_ingress_svc_subnet}
        type: LoadBalancer
        loadBalancerIP: ${demoapp_ingress_svc_ip}
        externalTrafficPolicy: Local
      config:
        use-forwarded-headers: "true"
