apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
spec:
  interval: 10m0s
  dependsOn:
    - name: infrastructure
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  healthChecks:
    - kind: Deployment
      name: session-checker
      namespace: demoapp
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-configs
