apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  prune: true
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: nginx
      namespace: nginx
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: chaos-mesh
      namespace: chaos-testing
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: flux-configs
