apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: infrastructure
        namespace: flux-system
      spec:
        path: ./flux/infrastructure/blue-dev
    target:
      kind: Kustomization
      name: infrastructure
      namespace: flux-system
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
      kind: Kustomization
      metadata:
        name: apps
        namespace: flux-system
      spec:
        path: ./flux/apps/blue-dev
    target:
      kind: Kustomization
      name: apps
      namespace: flux-system
