name: "CI for PR (flux)"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'flux/**'
  workflow_dispatch:
defaults:
  run:
    shell: bash
permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Diff files"
        id: diff
        working-directory: ./test/integration/scripts
        shell: bash -x {0}
        continue-on-error: true
        run: |
          echo 'DIFF_LOG<<EOF' >> $GITHUB_ENV
          ./diff-flux.sh >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV

      - name: "Create comment for PR (diff flux files between Blue & Green)"
        uses: actions/github-script@v6
        env:
          DIFF: "${{ env.DIFF_LOG }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Diff flux files between Blue & Green

            <details><summary>Show Diff</summary>

            \`\`\`\n
            ${process.env.DIFF}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
