name: "CI for PR (Terraform/Green)"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/green/**'
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Diff files"
        id: diff
        working-directory: ./test/scripts
        shell: bash -x {0}
        continue-on-error: true
        run: |
          ./diff-terraform.sh > ./diff.log
          DIFF_LOG=$(cat ./diff.log)
          DIFF_LOG="${DIFF_LOG//'%'/'%25'}"
          DIFF_LOG="${DIFF_LOG//$'\n'/'%0A'}"
          DIFF_LOG="${DIFF_LOG//$'\r'/'%0D'}"
          echo "::set-output name=DIFF_LOG::$DIFF_LOG"

      - name: "Create comment for PR (diff Terraform files between Blue & Green)"
        uses: actions/github-script@v4
        env:
          DIFF: "${{ steps.diff.outputs.DIFF_LOG }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Diff Terraform files between Blue & Green

            <details><summary>Show Diff</summary>

            \`\`\`\n
            ${process.env.DIFF}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: "Terraform Format"
        id: fmt
        working-directory: ./terraform/green
        run: terraform fmt -check

      - name: "Terraform Init"
        id: init
        working-directory: ./terraform/green
        run: terraform init -backend=false

      - name: "Terraform Validate"
        id: validate
        working-directory: ./terraform/green
        run: terraform validate -no-color

      - name: "Create comment for PR (Terraform fmt/validate/plan)"
        uses: actions/github-script@v4
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Check Terraform files (Green)
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`

            Please run ***terraform plan*** separately before merge, if necessary

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
