name: "CI for PR (Terraform/Green)"
on:
  pull_request:
    branches:
      - main
    paths:
      - 'terraform/green/**'
  workflow_dispatch:
defaults:
  run:
    shell: bash
permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  ci:
    name: "CI"
    runs-on: ubuntu-latest
    env:
      ARM_SUBSCRIPTION_ID: ${{  secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{  secrets.ARM_CLIENT_ID }}
      ARM_TENANT_ID: ${{  secrets.ARM_TENANT_ID }}

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Diff files"
        id: diff
        working-directory: ./test/integration/scripts
        shell: bash -x {0}
        continue-on-error: true
        run: |
          ./diff-terraform.sh > ./diff.log
          DIFF_LOG=$(cat ./diff.log)
          DIFF_LOG="${DIFF_LOG//'%'/'%25'}"
          DIFF_LOG="${DIFF_LOG//$'\n'/'%0A'}"
          DIFF_LOG="${DIFF_LOG//$'\r'/'%0D'}"
          echo "::set-output name=DIFF_LOG::$DIFF_LOG"

      - name: "Create comment for PR (diff Terraform files between Blue & Green)"
        uses: actions/github-script@v6
        env:
          DIFF: "${{ steps.diff.outputs.DIFF_LOG }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Diff Terraform files between Blue & Green

            <details><summary>Show Diff</summary>

            \`\`\`\n
            ${process.env.DIFF}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: "Setup Terraform"
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: "Terraform Format"
        id: fmt
        working-directory: ./test/integration
        run: make format-check-green

      - name: "Terraform Init"
        id: init
        working-directory: ./test/integration
        run: make init-green

      - name: "Setup TFLint"
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.40.0

      - name: "Run TFLint"
        id: tflint
        working-directory: ./test/integration
        run: make lint-green
        # Exit this job if tflint fails

      - name: "Terraform Validate"
        id: validate
        working-directory: ./test/integration
        run: make validate-green

      - name: "Terraform Plan"
        id: plan
        working-directory: ./test/integration
        run: make plan-green
        continue-on-error: true

      - name: "Create comment for PR (Terraform fmt/init/validate/plan)"
        uses: actions/github-script@v6
        env:
          PLAN: "${{ steps.plan.outputs.stdout }}\n${{ steps.plan.outputs.stderr }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Check Terraform files (Green)
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### TFLint 👓\`${{ steps.tflint.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            </details>

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
