apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-secrets-store-provider-azure
spec:
  chart:
    spec:
      chart: csi-secrets-store-provider-azure
      version: "0.2.1"
